apiVersion: v1

kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-password: c3RldmU=
  mysql-user: c3RldmU=
  root-password: c3RldmU=
  mysql-database: dGF3YXp1bi1kYg== # tawazun-db