apiVersion: v1

kind: Service
metadata:
  name: tawazun-service
spec:
  selector:
    app: tawazun
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30009