apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-dojo
  labels:
    app: ng-dep-dojo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ng-pod
  template:
    metadata:
      labels:
        app: ng-pod
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80