apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: c3RldmU= # Base64-encoded username
  password: ZXN0ZWJhbg== # Base64-encoded password
  basic-username: c3RldmU= # Base64-encoded username
  basic-password: ZXN0ZWJhbg== # Base64-encoded password