apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    team: production
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  hostPath:
    path: "/data"