apiVersion: v1

kind: Service
metadata:
  name: twentyfortyeight-service
spec:
  selector:
    app: my-2048
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007

# minikube service twentyfortyeight-service --url