apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
    - image: httpd
      name: web-container
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
    - image: redis
      name: redis-container
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir: {}