apiVersion: v1
kind: Pod
metadata:
  name: nginx-redis-memcached-pod
  annotations:
    author: "Stephan"
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
      - containerPort: 80
    - name: redis
      image: redis
    - name: memcached
      image: memcached

# kubectl apply -f 3-container.yml