apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-pod
  labels:
    app: nginx-replicas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      name: nginx web server
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

# kubectl apply -f nginx-rs.yml
# kubectl get pods -l 'app=nginx-server'